import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";
import StoreProvider from "@/app/lib/StoreProvider";

export const metadata = {
  title: "Neural evo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Navbar />
          {children}
          <Footer />
        </StoreProvider>     
      </body>
    </html>
  );
}
